  # This is a basic workflow to help you get started with Actions

name: Serial Scanner

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        type: string
        default: NARKOZ/hacker-scripts
        description: 'owner/repo format for example NARKOZ/hacker-scripts for https://github.com/NARKOZ/hacker-scripts'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          python3 -m pip install semgrep
          pip install -r requirements.txt
          pip install "tablib[xlsx]"
          python main.py ${{ secrets.GH_TOKEN }} ${{ inputs.repo }}
        shell: sh
        
      - name: artifact step 2
        uses: actions/upload-artifact@v3
        with:
          name: output-download
          path: output.xlsx
